// @flow
type Employee = {
  id: string,
  active: boolean,
  employeeRole: number,
  username: string,
  password: string,
  firstName: string,
  lastName: string,
  dateBirth: Date,
  email: string,
  phone: string,
  secondPhone: string,
  businessTitle: string,
  timeType: number,
  street: string,
  apartment: string,
  city: string,
  state: string,
  zipCode: string,
  hireDate: Date,
  createdAt: Date,
  createdBy: string,
  updatedAt: Date,
  updatedBy: null,
  deleteDate: null,
  deleteBy: null,
};
export type { Employee };
